---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: webserver
  namespace: flux-system
spec:
  chart:
    spec:
      verify:
        provider: cosign
        matchOIDCIdentity:
          - issuer: "^https://github.com/login/oauth$"
            subject: "^koray.oksay@gmail.com$"
      chart: webserver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: demo-charts
      version: 0.1.0
  interval: 5m0s
  releaseName: webserver
  targetNamespace: default
